#!/usr/bin/env bash

# @REM Oppgave 1-1:
if g++ -std=c++26 -Wall -Wextra -pedantic "oppgave 1-1.cpp" -o oppgave1-1; then
    echo "Success: Oppgave 1-1 compiled."
else 
    echo "Error: Compilation failed for Oppgave 1-1."
fi
echo ""


# @REM Oppgave 1-3:
if g++ -std=c++26 -Wall -Wextra -pedantic "oppgave 1-3.cpp" -o oppgave1-3; then
    echo "Success: Oppgave 1-3 compiled."
else 
    echo "Error: Compilation failed for Oppgave 1-3."
fi
